# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'

version: 2.1

orbs:

  node: circleci/node@4.1

workflows:

  sample: # This is the name of the workflow, feel free to change it to better match your workflow.

    jobs:

      - node/test:

          app-dir: ~/project/backend

          version: '15.1'

          pkg-manager: npm




